# alerting.yaml
# contains the configuration for the alerting mechanism of Gatus.

# endpoints-domain.yaml
# contains the configuration for the domain expiration checks of Gatus.

# endpoints-status.yaml
# contains the configuration for the status checks of Gatus.

# metrics.yaml
# contains the configuration for the metrics of Gatus.

# storage.yaml
# contains the configuration for the storage of Gatus.

# config.yaml
# main configuration file for Gatus

ui:
  default-sort-by: group