default-status: &defaults-status
  group: status-checks
  interval: 5m
  conditions:
    - "[STATUS] == 200"
  alerts:
    - type: slack

endpoints:
  - name: status-512area
    url: https://512area.com/
    <<: *defaults-status
  - name: status-best-no-deposit-casino-bonus
    url: https://best-no-deposit-casino-bonus.com/
    <<: *defaults-status
  - name: status-bingofreedeposit
    url: https://bingofreedeposit.com/
    <<: *defaults-status
  - name: status-freshology
    url: https://freshology.com/
    <<: *defaults-status
  - name: status-gamingstreet
    url: https://gamingstreet.com/
    <<: *defaults-status
  - name: status-globalpropertysystems
    url: https://globalpropertysystems.com/
    <<: *defaults-status
  - name: status-lotsballoonfest
    url: https://lotsballoonfest.com/
    <<: *defaults-status
  - name: status-rockheadsciences
    url: https://rockheadsciences.com/
    <<: *defaults-status
  - name: status-thewireplan
    url: https://thewireplan.com/
    <<: *defaults-status
